# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [11]:
# Import torch
import torch

# Create random tensor
X = torch.rand([7, 7])

X

tensor([[0.2674, 0.5699, 0.4222, 0.4845, 0.6957, 0.3282, 0.4263],
        [0.9197, 0.1826, 0.5997, 0.3199, 0.0710, 0.6909, 0.8535],
        [0.2689, 0.7753, 0.0272, 0.4575, 0.8145, 0.7395, 0.3530],
        [0.8498, 0.0724, 0.2815, 0.7489, 0.2048, 0.2537, 0.6566],
        [0.0726, 0.9486, 0.5161, 0.1457, 0.2009, 0.2421, 0.4008],
        [0.5122, 0.8546, 0.6450, 0.3473, 0.5273, 0.5135, 0.9071],
        [0.6792, 0.2326, 0.6342, 0.3500, 0.2059, 0.6546, 0.0843]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [13]:
# Create another random tensor
y = torch.rand([1, 7])
# y

# Perform matrix multiplication 
torch.matmul(X, y.T)

tensor([[1.3691],
        [1.7002],
        [1.5136],
        [1.3933],
        [1.3378],
        [2.0515],
        [1.1195]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [14]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
X = torch.rand([7, 7])
y = torch.rand([1, 7])

# Matrix multiply tensors
torch.matmul(X, y.T)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [15]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [19]:
# Set random seed
torch.cuda.manual_seed(1234)

# Check for access to GPU
torch.cuda.is_available()
# Create two random tensors on GPU
X = torch.rand([2, 3]).to("cuda:0")
Y = torch.rand([2, 3]).to("cuda:0")
X, Y

(tensor([[0.8102, 0.9801, 0.1147],
         [0.3168, 0.6965, 0.9143]], device='cuda:0'),
 tensor([[0.9351, 0.9412, 0.5995],
         [0.0652, 0.5460, 0.1872]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [22]:
# Perform matmul on tensor_A and tensor_B
Z = torch.matmul(X, Y.T)
Z

tensor([[1.7488, 0.6094],
        [1.4999, 0.5721]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [26]:
# Find max
max = Z.max()
# Find min
min = Z.min()
max, min

(tensor(1.7488, device='cuda:0'), tensor(0.5721, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [28]:
# Find arg max
max = Z.argmax()

# Find arg min
min = Z.argmin()

max, min

(tensor(0, device='cuda:0'), tensor(3, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [32]:
# Set seed
torch.manual_seed(7)

# Create random tensor
x = torch.rand([1, 1, 1, 10])

# Remove single dimensions
x = x.squeeze()

# Print out tensors and their shapes
x, x.shape

(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))